// src/components/Footer.svelte
<script lang="ts">
	import Fa from "svelte-fa"; // favicons
	import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
	import {
		faGithub,
		faFacebook,
		faInstagram,
	} from "@fortawesome/free-brands-svg-icons";;

	const links = [
		{
			name: "Github",
			href: "https:/github.com/12tqian",
			icon: faGithub,
			color: "#24292e",
		},
		{
			name: "Facebook",
			href: "https://fb.me/12tqian",
			icon: faFacebook,
			color: "#3b5998",
		},
		{
			name: "Email",
			href: "mailto:tcqian@mit.edu",
			icon: faEnvelope,
			color: "#333",
		},
		{
			name: "Instagram",
			href: "https://www.instagram.com/12tqian/",
			icon: faInstagram,
			color: "#333",
		},
	];
</script>

<footer class="p-6 pb-8 space-y-4">
	<div class="flex justify-center space-x-4">
		{#each links as link (link)}
			<a style="color: {link.color}" href={link.href}>
				<Fa
					icon={link.icon}
					size="2x"
					class="opacity-75 transition-opacity hover:opacity-100"
				/>
			</a>
		{/each}
	</div>
	<p class="text-center text-gray-400 font-light">
		Content by Timothy Qian, design <del>copied from</del> inspired by Eric Zhang :P
	</p>
</footer>

// src/app/components/Footer.tsx
import Link from "next/link";
import { FiGithub, FiLinkedin } from "react-icons/fi";
import { Mail } from "lucide-react";

const Footer: React.FC = () => {
  return (
    <footer className="layout-md py-4">
      <div className="flex flex-col items-center">
        <hr className="w-64 border-t border-gray-300 mb-4" />
        <div className="flex justify-center space-x-6">
          <Link
            href="https://github.com/12tqian"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 hover:text-black"
          >
            <FiGithub size={24} />
          </Link>
          <Link
            href="https://www.linkedin.com/in/12tqian"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 hover:text-black"
          >
            <FiLinkedin size={24} />
          </Link>
          <Link
            href="mailto:tcqian@mit.edu"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 hover:text-black"
          >
            <Mail size={24} />
          </Link>
        </div>
        <p className="text-gray-500 text-sm mt-4">
          Design inspired by{" "}
          <Link href="https://www.ekzhang.com" className="underline">
            {" "}
            Eric Zhang
          </Link>{" "}
          :)
        </p>
      </div>
    </footer>
  );
};

export { Footer };
