// src/components/Header.svelte
<script lang="ts">
	import { page } from '$app/stores';

	const links = [
		{ name: 'Home', href: '/' },
		{ name: 'Projects', href: '/projects' },
		{ name: 'Resume', href: '/resume' }
	];
</script>

<header>
	<h1 class="font-serif text-[2.8rem] mt-5 mb-2 text-center">Timothy Qian</h1>
	<nav
    class="flex justify-center text-xl sm:text-2xl font-light mb-4 space-x-3"
  >
		{#each links as link (link)}
			<a
				href={link.href}
				class="nav-link"
				class:active={$page.url.pathname === link.href}
			>
			{link.name}
		</a>
		{/each}
	</nav>
</header>

<style lang="postcss">
	.nav-link {
		@apply border-b border-transparent transition-colors text-blue-700;
	}

	.nav-link:is(:hover, .active) {
		@apply border-blue-700;
	}
</style>

// src/app/components/Header.tsx
"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { use } from "react";

const Navlink: React.FC<{
  href: string;
  label: string;
}> = ({ href, label }) => {
  const pathname = usePathname();
  const isActive =
    pathname === href || (href !== "/" && pathname.startsWith(href));

  return (
    <Link
      href={href}
      className={`${isActive ? "text-black" : "text-gray-500"} hover:text-black`}
    >
      {label}
    </Link>
  );
};

const links = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "Projects",
    href: "/projects",
  },
  {
    name: "Resume",
    href: "/resume",
  },
];

const Header: React.FC = () => {
  let pageTitle: string | null = null;
  const pathname = usePathname();

  links.forEach((link) => {
    if (link.href === pathname) {
      pageTitle = link.name;
    }
  });

  return (
    <nav className="w-full">
      <div className="container mx-auto flex justify-between items-center">
        <div className="text-xl">
          <Link href="/" className="text-black font-bold">
            Timothy Qian
          </Link>
          {pageTitle && <span className="text-black"> — {pageTitle}</span>}
        </div>
        <ul className="flex space-x-4 items-center text-black">
          {links.map((link) => (
            <li key={link.href} className="block ">
              <Navlink href={link.href} label={link.name} />
            </li>
          ))}
          {/* <li className="hidden md:block">
            <Navlink href="/" label="Home" />
          </li> */}
        </ul>
      </div>
    </nav>
  );
};

export { Header };
